# .golangci.yml
version: 2 # 建议使用一个较新的版本号

run:
  # 推荐设置，以处理大型项目
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - misspell # 启用 revive 核心命名检查 Linter
    - revive
  settings:
    misspell:
      locale: US 