// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// wireApp init kratos application.
func createApp() *App {
	string2 := CreateName()
	wireDb := CreateWireDb(string2)
	wireConfig := CreateWireConfig(wireDb)
	app := NewApp(wireConfig)
	return app
}
