// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: app/protobuf/city/city.proto

package city

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义一个 Person 消息
type City struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *City) Reset() {
	*x = City{}
	mi := &file_app_protobuf_city_city_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *City) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City) ProtoMessage() {}

func (x *City) ProtoReflect() protoreflect.Message {
	mi := &file_app_protobuf_city_city_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use City.ProtoReflect.Descriptor instead.
func (*City) Descriptor() ([]byte, []int) {
	return file_app_protobuf_city_city_proto_rawDescGZIP(), []int{0}
}

func (x *City) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *City) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_app_protobuf_city_city_proto protoreflect.FileDescriptor

const file_app_protobuf_city_city_proto_rawDesc = "" +
	"\n" +
	"\x1capp/protobuf/city/city.proto\x12\x04city\"4\n" +
	"\x04City\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddressB&Z$mikeian-for-golang/app/protobuf/cityb\x06proto3"

var (
	file_app_protobuf_city_city_proto_rawDescOnce sync.Once
	file_app_protobuf_city_city_proto_rawDescData []byte
)

func file_app_protobuf_city_city_proto_rawDescGZIP() []byte {
	file_app_protobuf_city_city_proto_rawDescOnce.Do(func() {
		file_app_protobuf_city_city_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_protobuf_city_city_proto_rawDesc), len(file_app_protobuf_city_city_proto_rawDesc)))
	})
	return file_app_protobuf_city_city_proto_rawDescData
}

var file_app_protobuf_city_city_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_protobuf_city_city_proto_goTypes = []any{
	(*City)(nil), // 0: city.City
}
var file_app_protobuf_city_city_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_protobuf_city_city_proto_init() }
func file_app_protobuf_city_city_proto_init() {
	if File_app_protobuf_city_city_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_protobuf_city_city_proto_rawDesc), len(file_app_protobuf_city_city_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_protobuf_city_city_proto_goTypes,
		DependencyIndexes: file_app_protobuf_city_city_proto_depIdxs,
		MessageInfos:      file_app_protobuf_city_city_proto_msgTypes,
	}.Build()
	File_app_protobuf_city_city_proto = out.File
	file_app_protobuf_city_city_proto_goTypes = nil
	file_app_protobuf_city_city_proto_depIdxs = nil
}
