// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: protobuf/person/person.proto

package person

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	city "mikeian-for-golang/app/protobuf/city"
	biz "mikeian-for-golang/internal/biz"
	openapi "mikeian-for-golang/third_party/openapi"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义一个 Person 消息
type Person struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                   `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	City          *city.City              `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Biz           *biz.Biz                `protobuf:"bytes,4,opt,name=biz,proto3" json:"biz,omitempty"`
	Api           *openapi.OpenApi        `protobuf:"bytes,5,opt,name=api,proto3" json:"api,omitempty"`
	Any           *anypb.Any              `protobuf:"bytes,6,opt,name=any,proto3" json:"any,omitempty"`
	Dv            *wrapperspb.DoubleValue `protobuf:"bytes,7,opt,name=dv,proto3" json:"dv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_protobuf_person_person_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_person_person_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_protobuf_person_person_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetCity() *city.City {
	if x != nil {
		return x.City
	}
	return nil
}

func (x *Person) GetBiz() *biz.Biz {
	if x != nil {
		return x.Biz
	}
	return nil
}

func (x *Person) GetApi() *openapi.OpenApi {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *Person) GetAny() *anypb.Any {
	if x != nil {
		return x.Any
	}
	return nil
}

func (x *Person) GetDv() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Dv
	}
	return nil
}

var File_protobuf_person_person_proto protoreflect.FileDescriptor

const file_protobuf_person_person_proto_rawDesc = "" +
	"\n" +
	"\x1cprotobuf/person/person.proto\x12\x06person\x1a\x18protobuf/city/city.proto\x1a\rbiz/biz.proto\x1a\x15openapi/openapi.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xe4\x01\n" +
	"\x06Person\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x1e\n" +
	"\x04city\x18\x03 \x01(\v2\n" +
	".city.CityR\x04city\x12\x1a\n" +
	"\x03biz\x18\x04 \x01(\v2\b.biz.BizR\x03biz\x12\"\n" +
	"\x03api\x18\x05 \x01(\v2\x10.openapi.OpenApiR\x03api\x12&\n" +
	"\x03any\x18\x06 \x01(\v2\x14.google.protobuf.AnyR\x03any\x12,\n" +
	"\x02dv\x18\a \x01(\v2\x1c.google.protobuf.DoubleValueR\x02dvB(Z&mikeian-for-golang/app/protobuf/personb\x06proto3"

var (
	file_protobuf_person_person_proto_rawDescOnce sync.Once
	file_protobuf_person_person_proto_rawDescData []byte
)

func file_protobuf_person_person_proto_rawDescGZIP() []byte {
	file_protobuf_person_person_proto_rawDescOnce.Do(func() {
		file_protobuf_person_person_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_person_person_proto_rawDesc), len(file_protobuf_person_person_proto_rawDesc)))
	})
	return file_protobuf_person_person_proto_rawDescData
}

var file_protobuf_person_person_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_person_person_proto_goTypes = []any{
	(*Person)(nil),                 // 0: person.Person
	(*city.City)(nil),              // 1: city.City
	(*biz.Biz)(nil),                // 2: biz.Biz
	(*openapi.OpenApi)(nil),        // 3: openapi.OpenApi
	(*anypb.Any)(nil),              // 4: google.protobuf.Any
	(*wrapperspb.DoubleValue)(nil), // 5: google.protobuf.DoubleValue
}
var file_protobuf_person_person_proto_depIdxs = []int32{
	1, // 0: person.Person.city:type_name -> city.City
	2, // 1: person.Person.biz:type_name -> biz.Biz
	3, // 2: person.Person.api:type_name -> openapi.OpenApi
	4, // 3: person.Person.any:type_name -> google.protobuf.Any
	5, // 4: person.Person.dv:type_name -> google.protobuf.DoubleValue
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protobuf_person_person_proto_init() }
func file_protobuf_person_person_proto_init() {
	if File_protobuf_person_person_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_person_person_proto_rawDesc), len(file_protobuf_person_person_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_person_person_proto_goTypes,
		DependencyIndexes: file_protobuf_person_person_proto_depIdxs,
		MessageInfos:      file_protobuf_person_person_proto_msgTypes,
	}.Build()
	File_protobuf_person_person_proto = out.File
	file_protobuf_person_person_proto_goTypes = nil
	file_protobuf_person_person_proto_depIdxs = nil
}
